### PR TITLE
Fix infinite request loop if metadata request fails

### LINKED ISSUE #3812: BUG: Metadata API Request Error Handling
**Describe the bug**
The UI does not utilise a retry limit or backoff for retrying Metadata API requests when the API is not available.

**To Reproduce**
1. Start the UI without an Aleph API available

**Expected behaviour**
The UI should retry a number of times delayed by some form of backoff. 

If a maximum number of retries is reached there should be some button to try again (refresh).

**Aleph version**
Current

**Screenshots**
network-error-spinning

**Additional context**

### PR DESCRIPTION
**Pull request by tillprochaska**
Fixes #3812. Previously, the UI would retry the metadata request indefinitely and without a delay. Now, if the metadata request fails, an error message and a button to reload the page are displayed.

I haven’t implemented automatic retries with back-offs for now, as this adds complexity and I’m not sure it’s necessary.

Screen Shot 2024-10-22 at 11 38 59

### CODE REVIEW

File: ui/src/app/Router.jsx [hunk 1]
```diff
@@ -60,11 +61,11 @@ class Router extends Component {
...
 
-    if (metadata.shouldLoad) {
+    if (metadata.shouldLoad && !metadata.isError) {
       this.props.fetchMetadata();
     }
 
-    if (messages.shouldLoad) {
+    if (messages.shouldLoad && !messages.isError) {
       this.fetchMessages();
     }
```
Comment (stchris) [inline ui/src/app/Router.jsx:70]: Noob question, but would it be possible to merge these two if clauses? They look identical to me.

Comment (stchris) [reply ui/src/app/Router.jsx:70]: I misread that, sorry. 😞

**Review by stchris — APPROVED** [review]
Very nice, I like the pragmatic change with the Reload button.

File: ui/src/app/Router.jsx (hunk 1 above)
Comment (tillprochaska) [reply ui/src/app/Router.jsx:70]: No problem, the two terms are indeed very similar :)
